options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west3-docker.pkg.dev/morodeer-bardaak/docker/autodoist:$COMMIT_SHA', '.']

  # Step 2: Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/morodeer-bardaak/docker/autodoist:$COMMIT_SHA']

images:
  - 'europe-west3-docker.pkg.dev/morodeer-bardaak/docker/autodoist:$COMMIT_SHA'

# You can define substitutions here
substitutions:
  _PORT: '8080'  # Example port number
